/**
 * Définitions de langues et détection automatique du layout clavier.
 * Chaque langue fournit un nom d'affichage, un label court, un alphabet
 * (pour le mode incohérent), et une liste de mots (pour le mode cohérent).
 */

/**
 * Détection du layout clavier via l'API Keyboard (Chromium, contexte sécurisé).
 * Retourne "qwerty" ou "azerty" en fonction de la position de KeyA.
 * Fallback : "qwerty".
 * @returns {Promise<"qwerty"|"azerty">}
 */
export async function detectKeyboardLayout() {
  if (typeof navigator === "undefined" || !navigator.keyboard) return "qwerty";
  try {
    const map = await navigator.keyboard.getLayoutMap();
    return map.get("KeyA") === "q" ? "azerty" : "qwerty";
  } catch {
    return "qwerty";
  }
}

/**
 * Banque de mots par langue (80-120 mots chacune).
 * Mots choisis pour être typables sans accents compliqués,
 * longueur 2-10 caractères, fréquence courante.
 */
const WORD_BANKS = {
  en: [
    "the","quick","brown","fox","jumps","over","lazy","dog","a","big",
    "red","car","on","road","and","was","very","fast","man","old",
    "new","way","may","day","try","ask","men","run","let","end",
    "put","say","she","use","how","its","kid","set","top","box",
    "few","got","job","own","pay","cut","red","sit","turn","unit",
    "build","come","find","give","hand","high","keep","last","long",
    "make","most","name","only","over","part","play","read","real",
    "run","same","tell","time","two","used","want","work","year",
    "about","after","again","being","below","black","board","bring",
    "caught","child","clean","close","could","cover","cross","drink",
    "earth","eight","every","found","green","house","large","learn",
    "might","never","night","often","point","river","small","sound",
    "start","still","study","their","thing","think","three","under",
    "water","where","which","world","would","write","young","green",
  ],
  fr: [
    "le","la","les","un","une","des","et","est","en","que","qui",
    "dans","du","au","ce","il","ne","sur","se","pas","plus",
    "par","je","avec","tout","faire","son","mais","comme","on","bien",
    "homme","femme","enfant","maison","chat","chien","ville","eau",
    "feu","terre","jour","nuit","temps","monde","grand","petit",
    "nouveau","vieux","bon","mauvais","rouge","bleu","vert","noir",
    "blanc","ici","porte","fenetre","table","chaise","lit","arbre",
    "fleur","route","pont","pierre","fer","bois","vin","pain",
    "lait","sel","mer","montagne","vallee","fleuve","ciel","soleil",
    "lune","etoile","orage","vent","pluie","neige","foin","lait",
    "beau","vrai","fort","rapide","lent","cher","loin","pres",
    "haut","bas","droit","gauche","rond","plat","sec","mou",
    "plein","vide","ancien","entier","juste","libre","serieux",
    "calme","franc","joie","peur","rire","pleurer","jouer","dormir",
    "manger","boire","courir","marcher","parler","lire","ecrire",
    "voir","entendre","sentir","toucher","apprendre","enseigner",
  ],
  es: [
    "el","la","los","las","un","una","y","es","en","que","de",
    "no","se","lo","por","con","para","como","pero","su","al",
    "hombre","mujer","niño","casa","gato","perro","ciudad","agua",
    "fuego","tierra","dia","noche","tiempo","mundo","grande","pequeno",
    "nuevo","viejo","bueno","malo","rojo","azul","verde","negro",
    "blanco","puerta","ventana","mesa","silla","arbol","flor",
    "camino","piedra","hierro","madera","vino","pan","leche",
    "sal","mar","montana","cielo","sol","luna","estrella","lluvia",
    "viento","nieve","bonito","verdad","fuerte","rapido","lento",
    "caro","lejos","cerca","alto","bajo","derecho","izquierda",
    "jugar","dormir","comer","beber","correr","caminar","hablar",
    "leer","escribir","ver","oír","sentir","aprender","enseñar",
    "trabajar","vivir","morir","nacer","crecer","pensar","saber",
    "poder","querer","llegar","pasar","quedar","volver","salir",
    "seguir","encontrar","llamar","llevar","dejar","poner","sentir",
  ],
  de: [
    "der","die","das","ein","eine","und","ist","in","den","von",
    "zu","mit","auf","fur","auch","noch","nach","wie","aber",
    "Mensch","Frau","Kind","Haus","Katze","Hund","Stadt","Wasser",
    "Feuer","Erde","Tag","Nacht","Zeit","Welt","gross","klein",
    "neu","alt","gut","schlecht","rot","blau","grun","schwarz",
    "weiss","Tur","Fenster","Tisch","Stuhl","Baum","Blume",
    "Weg","Stein","Eisen","Holz","Wein","Brot","Milch","Salz",
    "Meer","Berg","Himmel","Sonne","Mond","Stern","Regen","Wind",
    "schon","wahr","stark","schnell","langsam","teuer","nah","fern",
    "hoch","tief","gerade","rund","spiel","schlaf","ess","trink",
    "lauf","geh","sprech","les","schreib","seh","hor","fuhl",
    "lern","lehr","arbeit","leb","storb","denk","weis","kann",
    "will","komm","geh","bleib","zieh","find","ruf","nimm",
    "gib","leg","setz","halt","fuhl","kling","schein","weh",
  ],
  pt: [
    "o","a","os","as","um","uma","e","em","de","para","com",
    "que","por","nao","se","mais","como","mas","ao","sua","seu",
    "homem","mulher","crianca","casa","gato","cachorro","cidade","agua",
    "fogo","terra","dia","noite","tempo","mundo","grande","pequeno",
    "novo","velho","bom","mau","vermelho","azul","verde","preto",
    "branco","porta","janela","mesa","cadeira","arvore","flor",
    "caminho","pedra","ferro","madeira","vinho","pao","leite",
    "sal","mar","montanha","ceu","sol","lua","estrela","chuva",
    "vento","neve","bonito","verdade","forte","rapido","lento",
    "caro","longe","perto","alto","baixo","direito","esquerda",
    "jogar","dormir","comer","beber","correr","caminhar","falar",
    "ler","escrever","ver","ouvir","sentir","aprender","ensinar",
    "trabalhar","viver","morrer","nascer","crescer","pensar","saber",
    "poder","querer","chegar","passar","ficar","voltar","sair",
  ],
  it: [
    "il","lo","la","i","gli","le","un","una","e","in","di",
    "che","non","per","con","su","dal","come","ma","anche","dopo",
    "uomo","donna","bambino","casa","gatto","cane","citta","acqua",
    "fuoco","terra","giorno","notte","tempo","mondo","grande","piccolo",
    "nuovo","vecchio","buono","cattivo","rosso","blu","verde","nero",
    "bianco","porta","finestra","tavolo","sedia","albero","fiore",
    "strada","pietra","ferro","legno","vino","pane","latte","sale",
    "mare","montagna","cielo","sole","luna","stella","pioggia","vento",
    "bello","vero","forte","veloce","lento","caro","lontano","vicino",
    "alto","basso","giusto","libero","giocare","dormire","mangiare",
    "bere","correre","camminare","parlare","leggere","scrivere",
    "vedere","ascoltare","sentire","imparare","insegnare","lavorare",
    "vivere","morire","nascere","crescere","pensare","sapere","potere",
    "volere","arrivare","passare","tornare","uscire","seguire","trovare",
  ],
  nl: [
    "de","het","een","en","is","in","van","op","met","voor",
    "dat","niet","ook","maar","als","dan","nog","bij","uit","tot",
    "man","vrouw","kind","huis","kat","hond","stad","water",
    "vuur","aarde","dag","nacht","tijd","wereld","groot","klein",
    "nieuw","oud","goed","slecht","rood","blauw","groen","zwart",
    "wit","deur","raam","tafel","stoel","boom","bloem",
    "weg","steen","ijzer","hout","wijn","brood","melk","zout",
    "zee","berg","hemel","zon","maan","ster","regen","wind",
    "mooi","waar","sterk","snel","langzaam","duur","ver","dicht",
    "hoog","laag","rechts","links","rond","spel","slaap","eet",
    "drink","loop","praat","lees","schrijf","zie","hoor","voel",
    "leer","werk","leef","sterf","denk","weet","kan","wil",
    "kom","ga","blijf","vind","roep","neem","geef","leg",
  ],
  pl: [
    "i","w","nie","na","to","ze","sie","co","jak","ale",
    "czy","tak","juz","tylko","tez","przy","od","po","tym","gdy",
    "czlowiek","kobieta","dziecko","dom","kot","pies","miasto","woda",
    "ogień","ziemia","dzien","noc","czas","swiat","wielki","maly",
    "nowy","stary","dobry","zly","czerwony","niebieski","zielony","czarny",
    "biały","drzwi","okno","stol","krzeslo","drzewo","kwiat",
    "droga","kamien","zelazo","drewno","wino","chleb","mleko","sol",
    "morze","gora","niebo","slonce","ksiezyc","gwiazda","deszcz","wiatr",
    "ladny","prawda","silny","szybki","wolny","drogi","daleko","blisko",
    "wysoki","niski","prawo","lewo","okragly","graj","spi","jedz",
    "pij","biegaj","mow","czytaj","pisz","widz","sluchaj","czuj",
    "ucz","pracuj","zyj","umieraj","rodz sie","rosnij","mysl","wiesz",
    "miec","chciec","przyjsc","isc","zostac","znalezc","dac","polozyc",
  ],
  cs: [
    "a","v","je","se","na","to","z","ale","tak","jako",
    "za","jsem","byl","jsou","kdyz","jen","nebo","pod","pres","pred",
    "clovek","zena","dite","dum","kot","pes","mesto","voda",
    "ohen","zeme","den","noc","cas","svet","velky","maly",
    "novy","stary","dobry","spatny","cerveny","modry","zeleny","cerny",
    "bily","dvere","okno","stul","zidle","strom","kvety",
    "cesta","kamen","zelezo","drevo","vino","chlcb","mleko","sul",
    "more","hora","nebe","slunce","mesic","hvezda","detr","vitr",
    "pekný","pravda","silny","rychly","pomaly","drahy","daleko","blizko",
    "vysoky","nizky","pravo","levo","kruhovy","hrej","spi","jez",
    "pij","beze","mluv","ccti","pisc","vid","slyse","citem",
    "uc","pracuj","zij","umri","mysli","vis","mam","chci",
    "prid","jdi","zustan","najdi","dej","poloz","ber","drz",
  ],
  tr: [
    "bir","ve","bu","da","de","icin","ile","mi","var","ama",
    "ben","sen","biz","siz","onlar","o","ne","nasıl","neden","nerede",
    "adam","kadin","cocuk","ev","kopek","kedi","sehir","su",
    "ates","toprak","gun","gece","zaman","dunya","buyuk","kucuk",
    "yeni","eski","iyi","kotu","kirmizi","mavi","yesil","siyah",
    "beyaz","kapi","pencere","masa","sandalye","agac","cicek",
    "yol","tas","demir","odun","suc","ekmek","sut","tuz",
    "deniz","daga","gok","gunes","ay","yildiz","yagmur","ruzgar",
    "guzel","gercek","guclu","hizli","yavas","pahali","uzak","yakin",
    "yuksek","alca","sag","sol","yuvlak","oynau","uyu","ye",
    "ice","kos","yurut","konus","okuyaz","gors","dinle","hisset",
    "ogren","ogret","calis","yasa","ol","dusun","bil","ist",
    "gel","git","kal","bul","al","koy","birak","tut",
  ],
  hu: [
    "es","a","az","egy","nem","is","hogy","van","volt","meg",
    "mar","csak","ez","le","ki","fel","ha","te","en","mi",
    "ember","no","gyerek","haz","kutya","macska","varos","viz",
    "tuz","fold","ejjel","nap","ido","vilag","nagy","kis",
    "uj","regi","jo","rossz","piros","kek","zold","fekete",
    "feher","ajto","ablak","asztal","szek","fa","virag",
    "ut","ko","vas","fa","bor","kenyer","tej","so",
    "tenger","hegy","eg","nap","hold","csillag","eso","szel",
    "szep","igaz","eros","gyors","lassu","drag","tavol","kozel",
    "magas","alacsony","jobb","bal","kerek","jatszik","alszik","eszik",
    "iszik","fut","setal","beszel","olvas","ir","lat","hall",
    "erez","tanul","tanit","dolgozik","el","hal","gondolkodik","tud",
    "akar","jovet","megy","marad","talal","ad","tesz","fog",
  ],
  fi: [
    "ja","on","ei","se","tai","kun","tassa","ota","mutta","kuin",
    "olla","ole","tuli","tulee","meni","menee","saa","sai","antaa","annetaan",
    "mies","nainen","lapsi","talo","koira","kissa","kaupunki","vesi",
    "tuli","maa","paiva","yo","aika","maailma","suuri","pieni",
    "uusi","vanha","hyva","huono","punainen","sininen","vihrea","musta",
    "valkoinen","ovi","ikkuna","poyta","tuoli","puu","kukka",
    "tie","kivi","rauta","puu","viini","leipa","maito","suola",
    "meri","vuori","taivas","aurinko","kuu","tahdist","sade","tuuli",
    "kaunis","totuus","vahva","nopea","hidas","kaukana","lahella",
    "korkea","matala","oikea","vasen","pyorkea","pelaa","nukku","syod",
    "juo","juokse","kayve","puhu","lue","kirjoita","nae","kuule",
    "tunne","opi","opeta","tyoskentele","ela","kuole","ajattele","tieda",
  ],
  da: [
    "og","i","er","at","en","den","til","det","de","med",
    "ikke","har","for","kan","vil","skal","men","var","ogsaa","som",
    "mand","kvinde","barn","hus","kat","hund","by","vand",
    "ild","jord","dag","nat","tid","verden","stor","lille",
    "ny","gammel","god","dod","roed","blaa","gron","sort",
    "hvid","dor","vindue","bord","stol","trae","blomst",
    "vej","sten","jern","trae","vin","broed","milk","salt",
    "hav","bjerg","himmel","sol","maane","stjern","regn","vind",
    "flot","sand","stark","hurtig","langsom","dyr","fjern","naer",
    "hoej","lav","hoejre","venstre","rund","spil","sovn","spis",
    "drik","loebe","gaa","tale","laese","skrive","se","hoere",
    "foele","laere","undervise","arbejde","leve","doe","taenke","vide",
  ],
  sv: [
    "och","i","att","en","det","som","av","den","till","med",
    "har","inte","kan","ska","men","var","ocksaa","alla","finns","haer",
    "man","kvinna","barn","hus","katt","hund","stad","vatten",
    "eld","jord","dag","natt","tid","vaerld","stor","liten",
    "ny","gammal","bra","dalig","rod","bla","gron","svart",
    "vit","dor","fonster","bord","stol","trad","blomma",
    "vaeg","sten","jarn","trae","vin","brod","mjolk","salt",
    "hav","berg","himmel","sol","manna","stjarna","regn","vind",
    "fin","sanning","stark","snabb","langsam","dyr","fjarr","nar",
    "hoeg","lag","hoger","vanster","rund","spel","somm","aet",
    "drikk","loop","ga","tala","laes","skriv","se","hoer",
    "kann","laera","undervisa","arbeta","leva","doe","tanke","vet",
  ],
  no: [
    "og","i","er","at","en","den","til","det","de","med",
    "ikke","har","for","kan","vil","skal","men","var","ogsaa","som",
    "mann","kvinne","barn","hus","katt","hund","by","vann",
    "ild","jord","dag","natt","tid","verden","stor","liten",
    "ny","gammel","god","dod","rod","blaa","gronn","sort",
    "hvit","dor","vindu","bord","stol","tre","blomst",
    "vei","stein","jern","tre","vin","brød","melk","salt",
    "hav","fjell","himmel","sol","maane","stjerne","regn","vind",
    "fin","sannhet","sterk","rask","langsom","dyr","fjern","nar",
    "hoe","lav","hoeoyre","venstre","rund","spill","sovn","spis",
    "drikk","lop","ga","tale","les","skriv","se","hoer",
    "laer","undervis","arbeid","lev","doe","tenk","vit","vil",
  ],
  el: [
    "και","ειναι","σε","που","να","με","δεν","αυτο","απο","για",
    "οτι","αν","ηταν","πολυ","πως","μονο","αλλα","εδω","εκει","τοτε",
    "ανθρωπος","γυναικα","παιδι","σπιτι","γατα","σκυλι","πολη","νερο",
    "φωτια","γη","μερα","νυχτα","χρονος","κοσμος","μεγας","μικρος",
    "καινουργιος","παλιος","καλος","κακος","κοκκινος","μπλε","πρασινος","μαυρος",
    "ασπρος","πορτα","παραθυρο","τραπεζα","καρεκλα","δεντρο","λουλουδι",
    "δρομος","πετρα","σιδηρος","ξυλο","κρασι","ψωμι","γαλα","αλατι",
    "θαλασσα","βουνος","ουρανος","ηλιος","φεγγαρι","αστερι","βροχη","αερας",
    "ομορφος","αληθεια","δυνατος","γρηγορος","αργος","ακριβος","μακρια","κοντα",
    "ψηλος","χαμηλος","δεξια","αριστερα","στρογγυλος","παιχνιδι","υπνος","φαγωσε",
    "πιε","τρεξε","περπατησε","μιλησε","διαβασε","γραψε","δες","ακουσε",
    "νιωσε","μαθε","διδαξε","δουλεψε","ζησε","πεθανε","σκεψου","ξερε",
  ],
  ru: [
    "и","в","не","на","что","как","но","да","из","за",
    "по","от","до","для","при","уже","все","еще","тоже","или",
    "человек","женщина","ребёнок","дом","кошка","собака","город","вода",
    "огонь","земля","день","ночь","время","мир","большой","маленький",
    "новый","старый","хороший","плохой","красный","синий","зелёный","чёрный",
    "белый","дверь","окно","стол","стул","дерево","цвет",
    "дорога","камень","железо","дерево","вино","хлеб","молоко","соль",
    "море","гора","небо","солнце","луна","звезда","дождь","ветер",
    "красивый","правда","сильный","быстрый","медленный","дорогой","далеко","близко",
    "высокий","низкий","право","лево","круглый","играй","спи","ешь",
    "пей","беги","говори","читай","пиши","видь","слышь","чувство",
    "учи","работай","живи","умри","думай","знах","могу","хочу",
    "приди","иди","останься","найди","дай","положи","возьми","держи",
  ],
  ar: [
    "في","من","على","هذا","التي","الذي","لا","هو","كيف","لماذا",
    "ما","نحن","هم","مع","بعد","قبل","حتى","كل","بعض","قد",
    "رجل","امرأة","طفل","بيت","قط","كلب","مدينة","ماء",
    "نار","أرض","يوم","ليل","زمان","عالم","كبير","صغير",
    "جديد","قديم","جيد","سيء","أحمر","أزرق","أخضر","أسود",
    "أبيض","باب","نافذة","طاولة","كرسي","شجرة","زهرة",
    "طريق","حجر","حديد","خشب","نبيذ","خبز","حليب","ملح",
    "بحر","جبل","سماء","شمس","قمر","نجمة","مطر","رياح",
    "جميل","حقيقة","قوي","سريع","بطيء","غالي","بعيد","قريب",
    "عالي","منخفض","يمين","يسار","دائري","العب","نام","كل",
    "اشرب","اركض","امش","تحدث","اقرأ","اكتب","انظر","اسمع",
    "شعر","تعلم","علّم","اعمل","عش","مت","فكر","اعلم",
  ],
  ja: [
    "快速","茶色","狐","犬","猫","人","家","水",
    "火","土","日","夜","時","世界","大","小",
    "新","古","良","悪","赤","青","緑","黒",
    "白","窓","椅子","木","花","道","石",
    "鉄","木","酒","パン","牛乳","塩","海","山",
    "空","太陽","月","星","雨","風","美しい","真実",
    "強い","速い","遅い","高い","低い","右","左","丸い",
    "游ぶ","食べる","饮む","走る","歩く","話す","読む","書く",
    "見る","聞く","感じる","学ぶ","教える","働く","生きる","死ぬ",
    "考える","知る","出来る","欲しい","来る","行く","見つける","使う",
    "soku","hayai","cha","tori","inu","neko","hito","ie",
    "mizu","hi","tsuchi","yo","toki","sekai","ookii","chiisai",
    "atarashii","furui","yoi","warui","aka","ao","midori","kuro",
  ],
  ko: [
    "빠른","갈색","여우","개","고양이","사람","집","물",
    "불","땅","낮","밤","시간","세계","큰","작은",
    "새로운","오래된","좋은","나쁜","빨간","파란","초록","검은",
    "흰","문","창문","의자","나무","꽃","길","돌",
    "철","나무","와인","빵","우유","소금","바다","산",
    "하늘","태양","달","별","비","바람","아름다운","진실",
    "강한","빠른","느린","높은","낮은","오른쪽","왼쪽","둥근",
    "놀다","먹다","마시다","걷다","말하다","읽다","쓰다","보다",
    "듣다","느끼다","배우다","가르치다","일하다","살다","죽다","생각하다",
    "자다","앉다","서다","눕다","웃다","울다","닫다","열다",
    "들다","보다","만지다","걷다","뛰다","눕다","앉다","서다",
    "큰","작은","좋은","나쁜","새로운","빠른","느린","높은",
    "낮은","오른","왼쪽","큰","작은","좋은","나쁜","새로운",
  ],
  zh: [
    "快速","棕色","狐狸","狗","猫","人","家","水",
    "火","土","天","夜","时间","世界","大","小",
    "新","旧","好","坏","红","蓝","绿","黑",
    "白","门","窗","桌","椅","树","花",
    "路","石","铁","木","酒","面包","奶","盐",
    "海","山","天","太阳","月亮","星星","雨","风",
    "美","真实","强","快","慢","贵","远","近",
    "高","低","右","左","圆","玩","睡","吃",
    "喝","跑","走","说","读","写","看","听",
    "感觉","学","教","工作","活","死","想","知道",
    "kuai","cha","huli","gou","mao","ren","jia","shui",
  ],
  hi: [
    "तेज़","भूरा","लोमड़ी","कुत्ता","बिल्ली","आदमी","घर","पानी",
    "आग","ज़मीन","दिन","रात","समय","दुनिया","बड़ा","छोटा",
    "नया","पुराना","अच्छा","बुरा","लाल","नीला","हरा","काला",
    "सफ़ेद","दरवाज़ा","खिड़की","मेज़","कुर्सी","पेड़","फूल",
    "राप","पत्थर","लोहा","लकड़ी","शराब","रोटी","दूध","नमक",
    "समुद्र","पहाड़","आसमान","सूरज","चाँद","तारा","बारिश","हवा",
    "सुंदर","सच्चाई","मजबूत","तेज़","धीमा","महंगा","दूर","पास",
    "ऊँचा","नीचा","दायाँ","बायाँ","गोल","खेलो","सोओ","खाओ",
    "पीओ","भागो","चलो","बोलो","पढ़ो","लिखो","देखो","सुनो",
    "महसूस","सीखो","सिखाओ","काम करो","जीओ","मरो","सोचो","जानो",
  ],
  th: [
    "เร็ว","น้ำตาล","สุนัข","แมว","คน","บ้าน","น้ำ","ไฟ",
    "ดิน","กลางวัน","กลางคืน","เวลา","โลก","ใหญ่","เล็ก",
    "ใหม่","เก่า","ดี","ไม่ดี","แดง","น้ำเงิน","เขียว","ดำ",
    "ขาว","ประตู","หน้าต่าง","โต๊ะ","เก้าอี้","ต้นไม้","ดอกไม้",
    "ถนน","หิน","เหล็ก","ไม้","ไวน์","ขนมปัง","นม","เกลือ",
    "ทะเล","ภูเขา","ท้องฟ้า","พระอาทิตย์","พระจันทร์","ดาว","ฝน","ลม",
    "สวย","จริง","แรง","เร็ว","ช้า","แพง","ไกล","ใกล้",
    "สูง","ต่ำ","ขวา","ซ้าย","กลม","เล่น","นอน","กิน",
    "ดื่ม","วิ่ง","เดิน","พูด","อ่าน","เขียน","ดู","ฟัง",
    "รู้สึก","เรียน","สอน","ทำงาน","มีชีวิต","ตาย","คิด","รู้",
  ],
  vi: [
    "nhanh","nâu","cún","mèo","người","nhà","nước","lửa",
    "đất","ngày","đêm","thời gian","thế giới","lớn","nhỏ",
    "mới","cũ","tốt","xấu","đỏ","xanh","lục","đen",
    "trắng","cửa","cửa sổ","bàn","ghế","cây","hoa",
    "đường","đá","sắt","gỗ","rượu","bánh mì","sữa","muối",
    "biển","núi","trời","mặt trời","mặt trăng","ngôi sao","mưa","gió",
    "đẹp","thật","mạnh","nhanh","chậm","đắt","xa","gần",
    "cao","thấp","phải","trái","tròn","chơi","ngủ","ăn",
    "uống","chạy","đi","nói","đọc","viết","nhìn","nghe",
    "cảm giác","học","dạy","làm việc","sống","chết","nghĩ","biết",
  ],
};

/**
 * Liste complète des langues supportées.
 * `alphabet` est utilisé pour le mode incohérent.
 */
export const LANGUAGES = [
  { code: "en", name: "English",    flag: "🇬🇧", words: WORD_BANKS.en, alphabet: "abcdefghijklmnopqrstuvwxyz" },
  { code: "fr", name: "Français",   flag: "🇫🇷", words: WORD_BANKS.fr, alphabet: "abcdefghijklmnopqrstuvwxyzàâéèêëïîôùûüÿçœæ" },
  { code: "es", name: "Español",    flag: "🇪🇸", words: WORD_BANKS.es, alphabet: "abcdefghijklmnopqrstuvwxyzáéíóúñ¿¡" },
  { code: "de", name: "Deutsch",    flag: "🇩🇪", words: WORD_BANKS.de, alphabet: "abcdefghijklmnopqrstuvwxyzäöüß" },
  { code: "pt", name: "Português",  flag: "🇵🇹", words: WORD_BANKS.pt, alphabet: "abcdefghijklmnopqrstuvwxyzãõçáéíóú" },
  { code: "it", name: "Italiano",   flag: "🇮🇹", words: WORD_BANKS.it, alphabet: "abcdefghijklmnopqrstuvwxyzàèéìíîòóùú" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱", words: WORD_BANKS.nl, alphabet: "abcdefghijklmnopqrstuvwxyz" },
  { code: "pl", name: "Polski",     flag: "🇵🇱", words: WORD_BANKS.pl, alphabet: "aąbcćdeęfghijklłmnńoóprsśtuwyzźż" },
  { code: "cs", name: "Čeština",    flag: "🇨🇿", words: WORD_BANKS.cs, alphabet: "aábcčdďeéěfghchiíjklmnňoópqrřsštťuúůvwxyýzž" },
  { code: "tr", name: "Türkçe",     flag: "🇹🇷", words: WORD_BANKS.tr, alphabet: "abcçdefgğhıijklmnoöprsştuüvyz" },
  { code: "hu", name: "Magyar",     flag: "🇭🇺", words: WORD_BANKS.hu, alphabet: "aábcdeéfghiíjklmnoóöőpqrstuúüűvwxyz" },
  { code: "fi", name: "Suomi",      flag: "🇫🇮", words: WORD_BANKS.fi, alphabet: "abcdefghijklmnoprsštvzåäö" },
  { code: "da", name: "Dansk",      flag: "🇩🇰", words: WORD_BANKS.da, alphabet: "abcdefghijklmnopqrstuvwxyzæøå" },
  { code: "sv", name: "Svenska",    flag: "🇸🇪", words: WORD_BANKS.sv, alphabet: "abcdefghijklmnopqrstuvwxyzåäö" },
  { code: "no", name: "Norsk",      flag: "🇳🇴", words: WORD_BANKS.no, alphabet: "abcdefghijklmnopqrstuvwxyzæøå" },
  { code: "el", name: "Ελληνικά",   flag: "🇬🇷", words: WORD_BANKS.el, alphabet: "αβγδεζηθικλμνξοπρστυφχψω" },
  { code: "ru", name: "Русский",    flag: "🇷🇺", words: WORD_BANKS.ru, alphabet: "абвгдежзиклмнопрстуфхцчшщэюя" },
  { code: "ar", name: "العربية",    flag: "🇸🇦", words: WORD_BANKS.ar, alphabet: "ابتثجحخدذرزسشصضطظعغفقكلمنهوي" },
  { code: "ja", name: "日本語",      flag: "🇯🇵", words: WORD_BANKS.ja, alphabet: "abcdefghijklmnopqrstuvwxyz" },
  { code: "ko", name: "한국어",      flag: "🇰🇷", words: WORD_BANKS.ko, alphabet: "abcdefghijklmnopqrstuvwxyz" },
  { code: "zh", name: "中文",        flag: "🇨🇳", words: WORD_BANKS.zh, alphabet: "abcdefghijklmnopqrstuvwxyz" },
  { code: "hi", name: "हिन्दी",      flag: "🇮🇳", words: WORD_BANKS.hi, alphabet: "अआइईउऊएऐओऔकखगघचछजतदधनपबभमयरलवशषसह" },
  { code: "th", name: "ไทย",         flag: "🇹🇭", words: WORD_BANKS.th, alphabet: "กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮ" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳", words: WORD_BANKS.vi, alphabet: "aăâbcdđeêghiklmnoôơpqrstuưvxy" },
];

/**
 * Retourne une langue par son code.
 * @param {string} code
 * @returns {object|undefined}
 */
export function getLanguage(code) {
  return LANGUAGES.find((l) => l.code === code);
}

/**
 * Génère un mot aléatoire dans une langue donnée.
 * @param {string} code - Code de langue (ex: "fr")
 * @param {function} rng - Générateur aléatoire [0,1)
 * @returns {string}
 */
export function getRandomWord(code, rng) {
  const lang = getLanguage(code);
  if (!lang) return "word";
  return lang.words[Math.floor(rng() * lang.words.length)];
}

/**
 * Génère une séquence incohérente (3-8 caractères) dans l'alphabet de la langue.
 * @param {string} code - Code de langue
 * @param {function} rng - Générateur aléatoire [0,1)
 * @returns {string}
 */
export function generateIncoherentWord(code, rng) {
  const lang = getLanguage(code);
  if (!lang) return "xyz";
  const alpha = lang.alphabet;
  const len = 3 + Math.floor(rng() * 6);
  let word = "";
  for (let i = 0; i < len; i++) {
    word += alpha[Math.floor(rng() * alpha.length)];
  }
  return word;
}

/**
 * Traductions UI pour chaque langue supportée.
 * Clés : tous les textes affichés dans l'interface.
 */
export const UI_STRINGS = {
  en: {
    title: "Typing Speedtest",
    language: "Language",
    layout: "Layout",
    mode: "Mode",
    coherent: "Coherent",
    incoherent: "Incoherent",
    words: "Words",
    wpm: "WPM",
    accuracy: "Accuracy",
    time: "Time",
    hint: "Click on the text then type to start.",
    hintEsc: "Restart",
    done: "Done!",
    accuracyLabel: "% accuracy",
    restart: "Restart",
  },
  fr: {
    title: "Test de Vitesse de Frappe",
    language: "Langue",
    layout: "Disposition",
    mode: "Mode",
    coherent: "Cohérent",
    incoherent: "Incohérent",
    words: "Mots",
    wpm: "MPM",
    accuracy: "Précision",
    time: "Temps",
    hint: "Clique sur le texte puis tape pour démarrer.",
    hintEsc: "Recommencer",
    done: "Terminé !",
    accuracyLabel: "% précision",
    restart: "Recommencer",
  },
  es: {
    title: "Test de Velocidad de Escritura",
    language: "Idioma",
    layout: "Distribución",
    mode: "Modo",
    coherent: "Coherente",
    incoherent: "Incoherente",
    words: "Palabras",
    wpm: "PPM",
    accuracy: "Precisión",
    time: "Tiempo",
    hint: "Haz clic en el texto y empieza a escribir.",
    hintEsc: "Reiniciar",
    done: "¡Terminado!",
    accuracyLabel: "% precisión",
    restart: "Reiniciar",
  },
  de: {
    title: "Schreibgeschwindigkeitstest",
    language: "Sprache",
    layout: "Tastaturlayout",
    mode: "Modus",
    coherent: "Kohärent",
    incoherent: "Inkohärent",
    words: "Wörter",
    wpm: "WPM",
    accuracy: "Genauigkeit",
    time: "Zeit",
    hint: "Klicke auf den Text und tippe los.",
    hintEsc: "Neustart",
    done: "Fertig!",
    accuracyLabel: "% Genauigkeit",
    restart: "Neustart",
  },
  pt: {
    title: "Teste de Velocidade de Digitação",
    language: "Idioma",
    layout: "Layout",
    mode: "Modo",
    coherent: "Coerente",
    incoherent: "Incoerente",
    words: "Palavras",
    wpm: "PPM",
    accuracy: "Precisão",
    time: "Tempo",
    hint: "Clique no texto e comece a digitar.",
    hintEsc: "Reiniciar",
    done: "Concluído!",
    accuracyLabel: "% precisão",
    restart: "Reiniciar",
  },
  it: {
    title: "Test di Velocità di Battitura",
    language: "Lingua",
    layout: "Layout",
    mode: "Modalità",
    coherent: "Coerente",
    incoherent: "Incoerente",
    words: "Parole",
    wpm: "PPM",
    accuracy: "Precisione",
    time: "Tempo",
    hint: "Clicca sul testo e inizia a scrivere.",
    hintEsc: "Ricomincia",
    done: "Finito!",
    accuracyLabel: "% precisione",
    restart: "Ricomincia",
  },
  nl: {
    title: "Typsnelheidstest",
    language: "Taal",
    layout: "Indeling",
    mode: "Modus",
    coherent: "Coherent",
    incoherent: "Incoherent",
    words: "Woorden",
    wpm: "WPM",
    accuracy: "Nauwkeurigheid",
    time: "Tijd",
    hint: "Klik op de tekst en begin te typen.",
    hintEsc: "Opnieuw",
    done: "Klaar!",
    accuracyLabel: "% nauwkeurigheid",
    restart: "Opnieuw",
  },
  pl: {
    title: "Test Prędkości Pisania",
    language: "Język",
    layout: "Układ",
    mode: "Tryb",
    coherent: "Spójny",
    incoherent: "Niespójny",
    words: "Słowa",
    wpm: "CPM",
    accuracy: "Dokładność",
    time: "Czas",
    hint: "Kliknij tekst i zacznij pisać.",
    hintEsc: "Od nowa",
    done: "Gotowe!",
    accuracyLabel: "% dokładności",
    restart: "Od nowa",
  },
  cs: {
    title: "Test Rychlosti Psaní",
    language: "Jazyk",
    layout: "Rozložení",
    mode: "Režim",
    coherent: "Souvislý",
    incoherent: "Nesouvislý",
    words: "Slova",
    wpm: "ZPM",
    accuracy: "Přesnost",
    time: "Čas",
    hint: "Klikněte na text a začněte psát.",
    hintEsc: "Začít znovu",
    done: "Hotovo!",
    accuracyLabel: "% přesnosti",
    restart: "Začít znovu",
  },
  tr: {
    title: "Yazma Hızı Testi",
    language: "Dil",
    layout: "Düzen",
    mode: "Mod",
    coherent: "Tutarlı",
    incoherent: "Tutarsız",
    words: "Kelimeler",
    wpm: "DKM",
    accuracy: "Doğruluk",
    time: "Süre",
    hint: "Metne tıkla ve yazmaya başla.",
    hintEsc: "Yeniden başla",
    done: "Tamamlandı!",
    accuracyLabel: "% doğruluk",
    restart: "Yeniden başla",
  },
  hu: {
    title: "Gépelési Sebességteszt",
    language: "Nyelv",
    layout: "Kiosztás",
    mode: "Mód",
    coherent: "Koherens",
    incoherent: "Inkoherens",
    words: "Szavak",
    wpm: "SMP",
    accuracy: "Pontosság",
    time: "Idő",
    hint: "Kattints a szövegre és kezdj el gépelni.",
    hintEsc: "Újrakezd",
    done: "Kész!",
    accuracyLabel: "% pontosság",
    restart: "Újrakezd",
  },
  fi: {
    title: "Kirjoitusnopeustesti",
    language: "Kieli",
    layout: "Asettelu",
    mode: "Tila",
    coherent: "Johdonmukainen",
    incoherent: "Epäjohdonmukainen",
    words: "Sanat",
    wpm: "SPM",
    accuracy: "Tarkkuus",
    time: "Aika",
    hint: "Klikkaa tekstiä ja aloita kirjoittaminen.",
    hintEsc: "Aloita alusta",
    done: "Valmis!",
    accuracyLabel: "% tarkkuus",
    restart: "Aloita alusta",
  },
  da: {
    title: "Skrivhastighedstest",
    language: "Sprog",
    layout: "Tastaturlayout",
    mode: "Tilstand",
    coherent: "Kohærent",
    incoherent: "Inkohærent",
    words: "Ord",
    wpm: "OPM",
    accuracy: "Nøjagtighed",
    time: "Tid",
    hint: "Klik på teksten og begynd at skrive.",
    hintEsc: "Begynd forfra",
    done: "Færdig!",
    accuracyLabel: "% nøjagtighed",
    restart: "Begynd forfra",
  },
  sv: {
    title: "Skrivhastighetstest",
    language: "Språk",
    layout: "Tangentbordslayout",
    mode: "Läge",
    coherent: "Kohärent",
    incoherent: "Inkohärent",
    words: "Ord",
    wpm: "OPM",
    accuracy: "Träffsäkerhet",
    time: "Tid",
    hint: "Klicka på texten och börja skriva.",
    hintEsc: "Börja om",
    done: "Klar!",
    accuracyLabel: "% träffsäkerhet",
    restart: "Börja om",
  },
  no: {
    title: "Skrivhastighetstest",
    language: "Språk",
    layout: "Tastaturoppsett",
    mode: "Modus",
    coherent: "Kohærent",
    incoherent: "Inkohærent",
    words: "Ord",
    wpm: "OPM",
    accuracy: "Nøyaktighet",
    time: "Tid",
    hint: "Klikk på teksten og begynn å skrive.",
    hintEsc: "Begynn på nytt",
    done: "Ferdig!",
    accuracyLabel: "% nøyaktighet",
    restart: "Begynn på nytt",
  },
  el: {
    title: "Ταχύτητα Πληκτρολόγησης",
    language: "Γλώσσα",
    layout: "Διάταξη",
    mode: "Λειτουργία",
    coherent: "Συνεπής",
    incoherent: "Ασυνεπής",
    words: "Λέξεις",
    wpm: "ΛPA",
    accuracy: "Ακρίβεια",
    time: "Χρόνος",
    hint: "Κάντε κλικ στο κείμενο και πληκτρολογήστε.",
    hintEsc: "Ξαναρχίστε",
    done: "Τέλος!",
    accuracyLabel: "% ακρίβεια",
    restart: "Ξαναρχίστε",
  },
  ru: {
    title: "Тест Скорости Печати",
    language: "Язык",
    layout: "Раскладка",
    mode: "Режим",
    coherent: "Связный",
    incoherent: "Несвязный",
    words: "Слова",
    wpm: "СМН",
    accuracy: "Точность",
    time: "Время",
    hint: "Нажмите на текст и начните печатать.",
    hintEsc: "Начать заново",
    done: "Готово!",
    accuracyLabel: "% точности",
    restart: "Начать заново",
  },
  ar: {
    title: "اختبار سرعة الطباعة",
    language: "اللغة",
    layout: "التخطيط",
    mode: "الوضع",
    coherent: "متماسك",
    incoherent: "غير متماسك",
    words: "كلمات",
    wpm: "دقيقة",
    accuracy: "الدقة",
    time: "الوقت",
    hint: "انقر على النص وابدأ الكتابة.",
    hintEsc: "إعادة",
    done: "انتهى!",
    accuracyLabel: "% دقة",
    restart: "إعادة",
  },
  ja: {
    title: "タイピング速度テスト",
    language: "言語",
    layout: "レイアウト",
    mode: "モード",
    coherent: "一貫",
    incoherent: "不一致",
    words: "単語",
    wpm: "WPM",
    accuracy: "精度",
    time: "時間",
    hint: "テキストをクリックしてタイピングを開始。",
    hintEsc: "やり直す",
    done: "完了！",
    accuracyLabel: "% 精度",
    restart: "やり直す",
  },
  ko: {
    title: "타이핑 속도 테스트",
    language: "언어",
    layout: "레이아웃",
    mode: "모드",
    coherent: "일관",
    incoherent: "불일관",
    words: "단어",
    wpm: "WPM",
    accuracy: "정확도",
    time: "시간",
    hint: "텍스트를 클릭하고 타이핑을 시작하세요.",
    hintEsc: "다시 시작",
    done: "완료!",
    accuracyLabel: "% 정확도",
    restart: "다시 시작",
  },
  zh: {
    title: "打字速度测试",
    language: "语言",
    layout: "布局",
    mode: "模式",
    coherent: "连贯",
    incoherent: "不连贯",
    words: "单词",
    wpm: "WPM",
    accuracy: "准确率",
    time: "时间",
    hint: "点击文本开始打字。",
    hintEsc: "重新开始",
    done: "完成！",
    accuracyLabel: "% 准确率",
    restart: "重新开始",
  },
  hi: {
    title: "टाइपिंग गति परीक्षण",
    language: "भाषा",
    layout: "लेआउट",
    mode: "मोड",
    coherent: "सुसंगत",
    incoherent: "असंगत",
    words: "शब्द",
    wpm: "WPM",
    accuracy: "सटीकता",
    time: "समय",
    hint: "पर टेक्स्ट क्लिक करें और टाइपिंग शुरू करें।",
    hintEsc: "पुनरारंभ",
    done: "पूर्ण!",
    accuracyLabel: "% सटीकता",
    restart: "पुनरारंभ",
  },
  th: {
    title: "ทดสอบความเร็วการพิมพ์",
    language: "ภาษา",
    layout: "ผังปุ่ม",
    mode: "โหมด",
    coherent: "สอดคล้อง",
    incoherent: "ไม่สอดคล้อง",
    words: "คำ",
    wpm: "WPM",
    accuracy: "ความแม่นยำ",
    time: "เวลา",
    hint: "คลิกที่ข้อความแล้วเริ่มพิมพ์",
    hintEsc: "เริ่มใหม่",
    done: "เสร็จสิ้น!",
    accuracyLabel: "% ความแม่นยำ",
    restart: "เริ่มใหม่",
  },
  vi: {
    title: "Kiểm Tra Tốc Độ Gõ",
    language: "Ngôn ngữ",
    layout: "Bố cục",
    mode: "Chế độ",
    coherent: "Mạch lạc",
    incoherent: "Rời rạc",
    words: "Từ",
    wpm: "Từ/phút",
    accuracy: "Độ chính xác",
    time: "Thời gian",
    hint: "Nhấp vào văn bản và bắt đầu gõ.",
    hintEsc: "Bắt đầu lại",
    done: "Hoàn thành!",
    accuracyLabel: "% chính xác",
    restart: "Bắt đầu lại",
  },
};

/**
 * Retourne les chaînes UI pour une langue donnée.
 * Fallback sur l'anglais si la langue n'est pas supportée.
 * @param {string} code
 * @returns {object}
 */
export function getUIStrings(code) {
  return UI_STRINGS[code] ?? UI_STRINGS.en;
}
